version: '3.8'

services:
  api:
    build:
      context: ./FungEyeApi
      dockerfile: Dockerfile
    ports:
      - "5001:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production

  app:
    build:
      context: ./FungEyeApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  # add the FungEyeAi service here when it's ready to be containerized