services:
  api:
    image: fungeyeregistry.azurecr.io/fungeye-api:latest
    ports:
      - "5268:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - tfserving
    networks:
      - default

  app:
    image: fungeyeregistry.azurecr.io/fungeye-app:latest
    ports:
      - "8080:80"
    depends_on:
      - api

  tfserving:
    image: fungeyeregistry.azurecr.io/fungeye-tfserving:latest
    ports:
      - "8501:8501"
    environment:
      - MODEL_NAME=inception

  prometheus:
    image: fungeyeregistry.azurecr.io/fungeye-prometheus:latest
    ports:
      - "9090:9090"
    networks:
      - default

  grafana:
    image: fungeyeregistry.azurecr.io/fungeye-grafana:latest
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - default

  blackbox-exporter:
    image: fungeyeregistry.azurecr.io/fungeye-blackbox-exporter:latest
    ports:
      - "9115:9115"
    networks:
      - default

networks:
  default:
    name: fungeye-network