services:
  api:
    build:
      context: ./FungEyeApi/FungEyeApi
      dockerfile: Dockerfile
    ports:
      - "5268:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    depends_on:
      - tfserving
    networks:
      - default

  app:
    build:
      context: ./FungEyeApp
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  tfserving:
    image: tensorflow/serving:latest-gpu
    ports:
      - "8501:8501"
    environment:
      - MODEL_NAME=inception

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    networks:
      - default

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    depends_on:
      - prometheus
    networks:
      - default

  blackbox-exporter:
    image: prom/blackbox-exporter:latest
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
    ports:
      - "9115:9115"
    networks:
      - default

networks:
  default:
    name: fungeye-network