services:
  api:
    build:
      context: ./FungEyeApi/FungEyeApi
      dockerfile: Dockerfile
    ports:
      - "5268:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./secrets.json:/app/secrets.json:ro
      - ./FungEyeApi:/app/data
    depends_on:
      - tfserving

  app:
    build:
      context: ./FungEyeApp
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - api

  tfserving:
    image: tensorflow/serving:latest-gpu
    ports:
      - "8501:8501"
    volumes:
      - ./inception_v3_mushroomsv1_3_8:/models/inception/1
    environment:
      - MODEL_NAME=inception

networks:
  default:
    name: fungeye-network