apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    uid: prometheus    # Dodaj to pole
    editable: true     # Dodaj to pole
    jsonData:
      timeInterval: "5s"
      queryTimeout: "30s"
    version: 1         # Dodaj to pole